export const RESTURANT_LIST_REQUEST = 'RESTURANT_LIST_REQUEST';
export const RESTURANT_LIST_SUCCESS = 'RESTURANT_LIST_SUCCESS';
export const RESTURANT_LIST_FAIL = 'RESTURANT_LIST_FAIL';

export const RESTURANT_DETAILS_REQUEST = 'RESTURANT_DETAILS_REQUEST';
export const RESTURANT_DETAILS_SUCCESS = 'RESTURANT_DETAILS_SUCCESS';
export const RESTURANT_DETAILS_FAIL = 'RESTURANT_DETAILS_FAIL';

export const RESTURANT_REVIEW_CREATE_REQUEST = 'RESTURANT_REVIEW_CREATE_REQUEST';
export const RESTURANT_REVIEW_CREATE_SUCCESS = 'RESTURANT_REVIEW_CREATE_SUCCESS';
export const RESTURANT_REVIEW_CREATE_FAIL = 'RESTURANT_REVIEW_CREATE_FAIL';
export const RESTURANT_REVIEW_CREATE_RESET = 'RESTURANT_REVIEW_CREATE_RESET';
