export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";


export const USER_SIGNIN_REQUEST = "USER_SIGNIN_REQUEST";
export const USER_SIGNIN_SUCCESS = "USER_SIGNIN_SUCCESS";
export const USER_SIGNIN_FAIL = "USER_SIGNIN_FAIL";
export const USER_SIGNOUT= 'USER_SIGNOUT';

export const USER_ORDER_CREATE_REQUEST = 'USER_ORDER_REQUEST';
export const USER_ORDER_CREATE_SUCCESS = 'USER_ORDER_SUCCESS';
export const USER_ORDER_CREATE_FAIL = 'USER_ORDER_FAIL';
export const USER_ORDER_RESET = 'USER_ORDER_RESET'

export const USER_DETAILS_REQUEST = 'USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAIL = 'USER_DETAILS_FAIL';